--  08/10/2018
-- Fernanda Valle
-- Alejandro Cisneros Delevaux
-- La Gringa

-- MySQL Script generated by MySQL Workbench
-- Sun Aug  5 18:12:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`rubros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`rubros` (
  `idRubro` INT NOT NULL AUTO_INCREMENT,
  `rubro` VARCHAR(45) NOT NULL,
  `estado` CHAR(5) NULL DEFAULT 'a',
  PRIMARY KEY (`idRubro`),
  UNIQUE INDEX `uq_rubro` (`rubro` ASC))
ENGINE = InnoDB;

-- drop table productos;
-- -----------------------------------------------------
-- Table `proyecto`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `idRubro` INT NOT NULL,
  `producto` VARCHAR(50) NOT NULL,
  `estado` CHAR(5) NULL DEFAULT 'a',
  `precioVenta` DECIMAL(8,2) UNSIGNED NULL,
  `fechaActualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`),
   UNIQUE INDEX `uq_producto` (`producto` ASC),
	CONSTRAINT `fk_idRubro`
    FOREIGN KEY (`idRubro`)
    REFERENCES `proyecto`.`rubros` (`idRubro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- use proyecto;
-- drop table if exists etiquetas;
-- -----------------------------------------------------
-- Table `proyecto`.`etiquetas`
-- -------------------------------------------------

----
CREATE TABLE IF NOT EXISTS `proyecto`.`etiquetas` (
  `idEtiqueta` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `etiqueta` VARCHAR(45) NOT NULL,
  `estado` CHAR(5) NULL DEFAULT 'a',
  PRIMARY KEY (`idEtiqueta`),
  UNIQUE INDEX `uq_etiqueta` (`etiqueta` ASC),
    CONSTRAINT `fk_etiq_idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `proyecto`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `proyecto`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`empleados` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `rol` CHAR(5) NOT NULL DEFAULT 'v',
  `estado` CHAR(5) NOT NULL DEFAULT 'a',
  `observaciones` VARCHAR(45) NULL DEFAULT 'null',
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `uq_usuario` (`usuario` ASC),
  INDEX `idx_usuario` (`usuario` ASC),
  INDEX `idx_apellidoNombre` (`apellido` ASC, `nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`proveedores` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `razonSocial` VARCHAR(45) NOT NULL,
  `CUIT` VARCHAR(12) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(50) NULL,
  `estado` CHAR(5) NOT NULL DEFAULT 'a',
  `observaciones` VARCHAR(45) NULL DEFAULT 'null',
  PRIMARY KEY (`idProveedor`),
  UNIQUE INDEX `uq_razonSocial` (`razonSocial` ASC),
  UNIQUE INDEX `uq_CUIT` (`CUIT` ASC))
ENGINE = InnoDB;

-- drop table ventas;
-- -----------------------------------------------------
-- Table `proyecto`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`ventas` (
  `idVenta` INT  NOT NULL AUTO_INCREMENT,
  `idEmpleado` INT NOT NULL,
  `fecha`  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(8,2) NOT NULL,
  `observaciones` VARCHAR(50) NULL DEFAULT 'null',
  PRIMARY KEY (`idVenta`),
  INDEX `idx_fk_idEmpleado` (`idEmpleado` ASC),
  INDEX `idx_fecha` (`fecha` ASC),
  CONSTRAINT `fk_idEmpleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `proyecto`.`empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`lineasVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`lineasVenta` (
  `idVenta` INT NOT NULL ,
  `idProducto` INT NOT NULL,
  `cantidad` INT UNSIGNED NULL DEFAULT '1',
  `precioVenta` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idVenta`, `idProducto`),
  INDEX `idx_fk_idProducto` (`idProducto` ASC),
  INDEX `idx_fk_idVenta` (`idVenta` ASC),
  CONSTRAINT `fk_idVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `proyecto`.`ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `proyecto`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `proyecto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idProveedor` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(8,2) NULL,
  `estado` CHAR(5) NOT NULL DEFAULT 'p',
  `observaciones` VARCHAR(50) NULL DEFAULT 'null',
  INDEX `idx_fk_idEmpleado` (`idEmpleado` ASC),
  INDEX `idx_fk_Proveedor` (`idProveedor` ASC),
  INDEX `idx_fecha` (`fecha` ASC),
  PRIMARY KEY (`idPedido`, `idProveedor`),
  CONSTRAINT `fk_idEmp`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `proyecto`.`empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProv`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `proyecto`.`proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- use proyecto;
-- drop table compras;
-- drop table lineascompra;

-- -----------------------------------------------------
-- Table `proyecto`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`compras` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `idProveedor` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `fecha`  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `idx_fecha` (`fecha` ASC),
  INDEX `idx_fk_idPedidoIdProveedor` (`idPedido` ASC, `idProveedor` ASC),
  INDEX `idx_fk_idPedido` (`idPedido` ASC),
  INDEX `idx_fk_idProveedor` (`idProveedor` ASC),
  CONSTRAINT `fk_idPedidoIdProveedor`
    FOREIGN KEY (`idPedido` , `idProveedor`)
    REFERENCES `proyecto`.`pedidos` (`idPedido` , `idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idPedido`
	  FOREIGN KEY (`idPedido`)
	  REFERENCES `proyecto`.`pedidos` (`idPedido`)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProveedor`
	  FOREIGN KEY (`idProveedor`)
	  REFERENCES `proyecto`.`proveedores` (`idProveedor`)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION
  )
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `proyecto`.`lineasPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`lineasPedido` (
  `idProducto` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  `cantidad` INT UNSIGNED NULL DEFAULT 1,
  `precioPedido` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idProducto`, `idPedido`, `idProveedor`),
  INDEX `idx_fk_idProducto` (`idProducto` ASC),
  INDEX `idx_fk_idPedidoidProveedor` (`idPedido` ASC, `idProveedor` ASC),
  INDEX `idx_fk_idPedido` (`idPedido` ASC),
  INDEX `idx_fk_idProveedor` (`idProveedor` ASC),
  CONSTRAINT `fk_idPedidoIdProv`
    FOREIGN KEY (`idPedido` , `idProveedor`)
    REFERENCES `proyecto`.`pedidos` (`idPedido` , `idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProduc`
    FOREIGN KEY (`idProducto`)
    REFERENCES `proyecto`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`lineasCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`lineasCompra` (
  `idProducto` INT NOT NULL,
  `idCompra` INT NOT NULL,
  `cantidad` INT UNSIGNED NULL DEFAULT 1,
  `precioCompra` DECIMAL(8,2) NULL,
  PRIMARY KEY (`idProducto`, `idCompra`),
  INDEX `idx_fk_idCompra` (`idCompra` ASC),
  INDEX `idx_fk_idProducto` (`idProducto` ASC),
  CONSTRAINT `fk_idProduct`
    FOREIGN KEY (`idProducto`)
    REFERENCES `proyecto`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCompra`
    FOREIGN KEY (`idCompra`)
    REFERENCES `proyecto`.`compras` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
